import Head from 'next/head';
import Footer from '../components/Footer';
import HeroImage from '../components/HeroImage';
import Navbar from '../components/Navbar';

const project_nublar = '/images/project_nublar/squad.jpg'
const studio = '/images/studio/modeler.png'
const dumb_library = '/images/dumb_library.bmp'
const gradlehook = '/images/gradle_hook.bmp'

const HomePage = () => {

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="bg-gray-800 text-white">

        <section className="w-screen h-screen">
          <div className="transform translate-y-1/3 h-full translate-x-44">
            <div className="flex flex-row">
              <h1 className="text-6xl font-semibold">DumbCode</h1>
              <div className="h-2 w-8 bg-white mt-12 ml-3 bottom-0 animate-pulse"></div>
            </div>
            <p className="font-semibold text-md ml-1">Re-inventing the way you play Minecraft.</p>
          </div>
        </section>

        <HeroImage image={studio} />
        <HeroImage image={project_nublar} />
        <HeroImage image={dumb_library} />
        <HeroImage image={gradlehook} />

      </div>
      <Footer />
    </div>
  );
}

export default HomePage;
