import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';


const banner = '/images/project_nublar/squad.jpg'
const project_nublar = '/images/project_nublar/brachi.jpg'
const dumb_library = '/images/dumb_library.bmp'
const gradlehook = '/images/gradle_hook.bmp'

const project = '/images/studio/project.png'
const modeler = '/images/studio/modeler.png'
const mapper = '/images/studio/mapper.png'
const texturer = '/images/studio/texturer.png'
const animator = '/images/studio/animator.png'

const HomePage = () => {

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>DumbCode Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="bg-neutral-800 text-white">

        <section className="w-screen h-screen bg-cover bg-center" style={{ backgroundImage: `url(${banner})` }}>
          <div className="translate-y-1/3 h-full translate-x-44">
            <div className="flex flex-row">
              <h1 className="text-6xl font-semibold">DumbCode</h1>
              <div className="h-2 w-8 bg-white mt-12 ml-3 bottom-0 animate-pulse"></div>
            </div>
            <p className="font-semibold text-md ml-1">Re-inventing the way you play Minecraft.</p>
          </div>
        </section>

        <section className="h-screen w-screen flex flex-row">
          <div className="text-center lg:text-left translate-y-1/3 h-full lg:translate-x-44 w-full xl:w-auto">
            <div>
              <h1 className="text-xl font-semibold -mb-2 text-neutral-500">POWERED BY:</h1>
              <h1 className="text-6xl font-semibold">DumbCode Studio</h1>
            </div>
            <p className="font-semibold text-md text-neutral-500 ml-1">A full featured game asset creation tool.</p>
            <button className="bg-blue-500 hover:bg-blue-600 p-2 mt-12 rounded-md">View More</button>
          </div>
          <div className="relative left-40 place-self-center translate-x-full hidden 2xl:block">
            <div className="text-center group rounded-md bg-yellow-500 aspect-video w-96 translate-y-1/2 -translate-x-8 -rotate-12 hover:scale-150 transition-transform hover:relative hover:rotate-0 hover:translate-x-0 shadow-md hover:shadow-2xl hover:z-50 bg-center bg-cover" style={{ backgroundImage: `url(${project})` }}>
              <p className="bg-purple-500 rounded-xl w-48 rotate-12 -translate-x-24 group-hover:translate-x-24 group-hover:-translate-y-4 group-hover:rotate-0 transition-transform px-2 shadow-xl">Project Management</p>
            </div>
            <div className="text-center group rounded-md bg-red-500 aspect-video w-96 translate-y-10 -rotate-6 hover:scale-150 transition-transform hover:relative hover:rotate-0 shadow-md hover:shadow-2xl hover:z-50 bg-center bg-cover" style={{ backgroundImage: `url(${modeler})` }}>
              <p className="bg-blue-500 rounded-xl w-48 rotate-6 -translate-x-24 group-hover:translate-x-24 group-hover:-translate-y-4 group-hover:rotate-0 transition-transform px-2 shadow-xl">Modeler</p>
            </div>
            <div className="text-center group rounded-md bg-green-500 aspect-video w-96 z-10 translate-x-5 hover:scale-150 transition-transform hover:relative hover:translate-x-0 shadow-md hover:shadow-2xl hover:z-50 bg-center bg-cover" style={{ backgroundImage: `url(${mapper})` }}>
              <p className="bg-teal-500 rounded-xl w-48 -translate-x-24 group-hover:translate-x-24 group-hover:-translate-y-4 transition-transform px-2 shadow-xl">Texture Mapper</p>
            </div>
            <div className="text-center group rounded-md bg-blue-500 aspect-video w-96 -translate-y-10 rotate-6 hover:scale-150 transition-transform hover:relative hover:rotate-0 shadow-md hover:shadow-2xl hover:z-50 bg-center bg-cover" style={{ backgroundImage: `url(${texturer})` }}>
              <p className="bg-green-500 rounded-xl w-48 -rotate-6 -translate-x-24 group-hover:translate-x-24 group-hover:-translate-y-4 group-hover:rotate-0 transition-transform px-2 shadow-xl">Texturer</p>
            </div>
            <div className="text-center group rounded-md bg-purple-500 aspect-video w-96 -translate-y-1/2 -translate-x-8 rotate-12 hover:scale-150 transition-transform hover:relative hover:rotate-0 hover:translate-x-0 shadow-md hover:shadow-2xl hover:z-50 bg-center bg-cover" style={{ backgroundImage: `url(${animator})` }}>
              <p className="bg-yellow-500 rounded-xl w-48 -rotate-12 -translate-x-24 group-hover:translate-x-24 group-hover:-translate-y-4 group-hover:rotate-0 transition-transform px-2 shadow-xl">Animator</p>
            </div>
          </div>
          <div>

          </div>
        </section>

      </div>
      <Footer />
    </div>
  );
}

export default HomePage;
